=== DawnScience/dawn-common/org.dawb.common.util/src/org/dawb/common/util/xml/dad.xsd
<?xml version="1.0" encoding="ISO-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="acquisitionType">
      <xs:restriction base="xs:string">
        <xs:enumeration value="MGfrelon2k"/>
        <xs:enumeration value="MGmono"/>
       </xs:restriction>
    </xs:simpleType>

    <xs:element name="userField" >
      <xs:complexType>
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="value" type="xs:string" />
      </xs:complexType>
    </xs:element>
    
    <xs:element name="scanField">
      <xs:complexType>
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="value" type="xs:string" />
      </xs:complexType>
    </xs:element>

    <xs:element name="acquisition">
      <xs:complexType>
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="mg" type="acquisitionType" />
      </xs:complexType>
    </xs:element>

    <xs:element name="scan">
      <xs:complexType>
        <xs:sequence>
          <xs:element ref="scanField"    minOccurs="0" maxOccurs="unbounded"/>
          <xs:element ref="acquisition"  minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" />
      </xs:complexType>
    </xs:element>

    <xs:element name="sequence">
    
      <xs:complexType>
        <xs:sequence>
          <xs:element ref="userField"   minOccurs="0" maxOccurs="unbounded"/>
          <xs:element ref="acquisition" minOccurs="1" maxOccurs="unbounded"/>
          <xs:element ref="scan"        minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" />
        <xs:attribute name="name" type="xs:string" />
      </xs:complexType>
      
    </xs:element>
    
</xs:schema>

=== DawnScience/dawn-common/org.dawb.common.ui/src/org/dawb/common/ui/project/sequence.xml
<?xml version="1.0" encoding="UTF-8"?>

<sequence id="001"
          name="ID21 FFE dec.2010"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="/users/gerring/Desktop/dad.xsd">

  <userField name="User Name"   value="Michel Strogoff"/>
  <userField name="Sample Name" value="Kryptonite"/>

  <acquisition name="Dark for White" mg="MGfrelon2k"/>
  <acquisition name="Dark for data" mg="MGfrelon2k"/>

  <scan name="scan 001">
    <scanField name="Start Value" value="" />
    <scanField name="End Value" value="" />
    <scanField name="Steps" value="" />

    <acquisition name="MonoPos" mg="MGmono" />
    <acquisition name="White before" mg="MGfrelon2k"/>
    <acquisition name="Data" mg="MGfrelon2k" />
    <acquisition name="White after" mg="MGfrelon2k" />
  </scan>


</sequence>
